@echo off
echo Resetting...
git reset
echo Adding Backend...
git add Aether/backend
echo Committing Backend...
git commit -m "feat(backend): implement content versioning and diff API"
echo Adding Frontend...
git add Aether/frontend
echo Committing Frontend...
git commit -m "feat(frontend): add version history UI and diff viewer"
echo Status...
git status
