#!/usr/bin/env python3
import os
import sys

def create_file(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)
    print(f"✅ Created: {path}")

def scaffold_kb():
    print("🏗️  Aether KB Scaffolder")
    print("----------------------")
    
    kb_id = input("Enter KB ID (e.g. music_v1): ").strip()
    kb_name = input("Enter KB Name (e.g. Music Theory): ").strip()
    
    if not kb_id or not kb_name:
        print("❌ Invalid input")
        return

    # 1. Workflow
    workflow_path = f".agent/workflows/new_kb_{kb_id}.md"
    workflow_content = f"""---
description: Implementation Plan for {kb_name}
---
# Plan: {kb_name} ({kb_id})
- [ ] Backend: Add renderer_id '{kb_id}' support
- [ ] Frontend: Create layout for '{kb_id}'
"""
    create_file(workflow_path, workflow_content)

    # 2. Frontend Layout Placeholder
    layout_path = f"frontend/src/views/kb/layouts/{kb_id.capitalize()}Layout.vue"
    layout_content = f"""<template>
  <div class="kb-layout-{kb_id}">
    <h1>{kb_name}</h1>
    <slot />
  </div>
</template>

<script setup lang="ts">
// Generated by scaffold_kb.py
</script>
"""
    create_file(layout_path, layout_content)
    
    # 3. Spec
    spec_path = f"AI/context/specs/{kb_id}_spec.md"
    spec_content = f"# Spec: {kb_name}\n\nRenderer ID: `{kb_id}`\n\n## Requirements\n- [ ] Define Schema\n"
    create_file(spec_path, spec_content)

    print("\n✅ Scaffold Complete!")
    print(f"1. A Plan was created at: {workflow_path}")
    print(f"2. A Spec was created at: {spec_path}")
    print(f"3. A Vue Layout was created at: {layout_path}")
    print("\n👉 Next Step: 'Please implement the features described in the generated plan.'")

if __name__ == "__main__":
    scaffold_kb()
